import { theme, Button } from 'antd';
import { coverage, guideChapters, nextSteps } from '../design-system/handbook';
import { palette } from '../design-system/theme';
import { Avatar, FoodSticker } from './Illustrations';
import { StatusLabel } from './Playgrounds';

export function DesignerHandbook() {
 const {token:t}=theme.useToken();
 const colors=[['品牌蓝','主操作、品牌标记',t.colorPrimary,t.colorTextLightSolid],['悬停蓝','鼠标停留',t.colorPrimaryHover,t.colorTextLightSolid],['按下蓝','按下反馈',t.colorPrimaryActive,t.colorTextLightSolid],['选中底色','导航与选项背景',t.colorPrimaryBg,t.colorPrimaryText],['匹配','配合勾选与短标签',t.colorSuccessBg,t.colorSuccessText],['不符','配合警示与原因',t.colorErrorBg,t.colorErrorText],['待确认','配合问号与询问操作',t.colorWarningBg,t.colorWarningText],['信息','辅助说明',t.colorInfoBg,t.colorInfoText]];
 const types=[['一级标题',t.fontSizeHeading1,t.lineHeightHeading1],['二级标题',t.fontSizeHeading2,t.lineHeightHeading2],['三级标题',t.fontSizeHeading3,t.lineHeightHeading3],['四级标题',t.fontSizeHeading4,t.lineHeightHeading4],['五级标题',t.fontSizeHeading5,t.lineHeightHeading5],['大正文',t.fontSizeLG,t.lineHeightLG],['正文',t.fontSize,t.lineHeight],['辅助文字',t.fontSizeSM,t.lineHeightSM]] as const;
 const spaces=[t.paddingXXS,t.paddingXS,t.paddingSM,t.padding,t.paddingLG,t.paddingXL];
 const Chapter=({index}:{index:number})=>{const c=guideChapters[index];return <section id={`guide-${c.id}`} className="guide-section"><div className="guide-heading"><h2>{c.title}</h2><span className="source-label">{c.status}</span></div><ul className="guide-rules">{c.rules.map(r=><li key={r}>{r}</li>)}</ul></section>};
 return <div className="designer-guide">
  <div className="guide-verdict"><span className="eyebrow">DESIGN REVIEW · 2026.09.21</span><h2>基础已就绪，完整体验尚未闭环。</h2><p>现在可以开始逐页设计。还不能把这套规范称为完整产品系统：核心拍照舞台、业务反馈与移动端细节仍需补齐。以下把“已实现”和“待确认”分开展示，不以百分比代替完成证据。</p><Button onClick={()=>window.print()}>打印 / 保存为 PDF</Button></div>
  <nav className="guide-index" aria-label="手册目录">{[['audit','完整性检查'],['identity','视觉原则'],['colors','颜色'],['type','文字'],['layout','布局'],['geometry','尺寸与质感'],['components','组件'],['avatar','人物'],['motion','动效'],['content','图标与文案'],['access','移动与无障碍'],['handoff','交付'],['next','补齐顺序']].map(([id,name])=><a key={id} href={`#guide-${id}`}>{name}</a>)}</nav>
  <section id="guide-audit" className="guide-section"><h2>完整性检查</h2><p className="muted">“已实现”指当前规范基础；“示例可用”不代表最终设计已获确认。“尚未实现”指产品流程，不是 Ant Design 没有对应能力。</p><div className="table-scroll"><table className="token-table guide-table"><thead><tr><th>范围</th><th>现状</th><th>判断与缺口</th><th>依据</th></tr></thead><tbody>{coverage.map(([area,status,detail,evidence])=><tr key={area}><th scope="row">{area}</th><td>{status}</td><td>{detail}</td><td>{evidence}</td></tr>)}</tbody></table></div></section>
  <Chapter index={0}/>
  <section id="guide-colors" className="guide-section"><h2>02 颜色：每种颜色有明确分工</h2><div className="guide-grid">{colors.map(([name,use,bg,fg])=><article className="guide-swatch" key={name}><div style={{background:bg,color:fg}}><strong>{name}</strong><span>{bg.toUpperCase()}</span></div><p>{use}</p><small>文字色 {fg.toUpperCase()}</small></article>)}</div><div className="guide-status"><StatusLabel state="match"/><StatusLabel state="conflict"/><StatusLabel state="unknown"/></div><p>页面以白色 {t.colorBgContainer} 为主，浅灰 {t.colorBgLayout} 分区；正文 {t.colorText}，辅助文字 {t.colorTextSecondary}，常规边框 {t.colorBorder}。状态使用浅底深字，不在明黄、亮绿上直接叠白色小字。</p><details><summary>查看全部辅助色与原始色值</summary><div className="guide-palette">{Object.entries(palette).map(([name,color])=><span key={name}><i style={{background:color}}/>{name} · {color}</span>)}</div><p>辅助色用于人物、食物与装饰，不取代品牌蓝。原始色板与上方语义底色/文字色不是同一组值。</p></details></section>
  <section id="guide-type" className="guide-section"><h2>03 字体：先用层级，再控制文字量</h2><p>使用系统字体，继承 Ant Design；字体家族如下。标题字重 {t.fontWeightStrong}，普通正文使用常规字重。表中为基础字号，手机规范站的主标题会降为二级标题；产品各页仍需具体选择。</p><details><summary>查看字体家族</summary><p className="guide-code">{t.fontFamily}</p></details>{types.map(([name,size,line],i)=><div className="guide-type-row" key={name}><span>{name}<small>{size}px / 行高 {(size*line).toFixed(0)}px</small></span><p style={{fontSize:size,lineHeight:line,fontWeight:i<5?t.fontWeightStrong:400}}>每一口，都更懂你。<br/><span lang="en">A little curiosity.</span></p></div>)}</section>
  <Chapter index={1}/>
  <section id="guide-geometry" className="guide-section"><h2>05 间距、尺寸与质感</h2><p>下列数值直接读取当前主题。按现有间距档位建立疏密关系；具体页面边距随逐页设计确认，不另造基础刻度。</p><div className="guide-measures">{spaces.map((v,i)=><div key={i}><span>{v}px</span><i style={{width:v,background:t.colorPrimary}}/></div>)}</div><div className="guide-grid">{[['小圆角',t.borderRadiusSM],['常规圆角',t.borderRadius],['大圆角',t.borderRadiusLG]].map(([name,v])=><article className="guide-shape" key={name}><div style={{borderRadius:Number(v),border:`${t.lineWidth}px solid ${t.colorBorder}`,background:t.colorPrimaryBg}}>{name}<br/>{v}px</div></article>)}</div><p>描边 {t.lineWidth}px；小 / 常规 / 大控件高度：{t.controlHeightSM} / {t.controlHeight} / {t.controlHeightLG}px。视觉高度与可点击区域是两件事，移动端还需单独检查触控面积。</p><div className="guide-status"><Button size="small">小按钮</Button><Button>常规按钮</Button><Button size="large" type="primary">主要操作</Button><Button disabled>禁用</Button><Button loading>加载</Button></div><div className="guide-grid"><div className="guide-elevation" style={{boxShadow:t.boxShadow}}>基础浮层阴影<small>沿用 Ant Design 默认值</small></div><div className="guide-elevation" style={{boxShadow:t.boxShadowSecondary}}>次级浮层阴影<small>沿用 Ant Design 默认值</small></div></div><p>基础动效：快 {t.motionDurationFast}、中 {t.motionDurationMid}、慢 {t.motionDurationSlow}；吃食物样例使用慢速 × 4（{(parseFloat(t.motionDurationSlow)*4).toFixed(1)} 秒）。这是当前样例节奏，完整电影式分镜尚未定稿。</p></section>
  <Chapter index={2}/>
  <div className="guide-art" aria-label="人物与食物示例"><Avatar/><FoodSticker/><div><strong>同一个人物，贯穿每一幕。</strong><p>配置与动作共用形象。此处为原创示意资产。</p></div></div>
  {[3,4,5,6,7].map(index=><Chapter key={index} index={index}/>)}
  <section id="guide-next" className="guide-section"><h2>12 接下来按流程补齐</h2><p>不需要先把所有组件都做完。优先补支撑主线的规则，再在实际页面中验证。</p><div className="guide-grid">{nextSteps.map(([stage,title,desc])=><article className="rule-card" key={title}><span className="source-label">{stage}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></section>
 </div>;
}
